/**
 *  image_map_tagger.js
 *
 *  Created on: April 12, 2013
 *      Author: Valeri Karpov
 *
 *  Generate image maps for the tags on a given look, intended to be used with
 *  images generated by gmTagger.
 *
 */

exports.imageMapTagger = function(gmTagger) {
  return function(look, callback) {
    var checkTaggedUrl = function(callback) {
      if (!look.taggedUrl) {
        gmTagger(look, callback);
      } else {
        callback(null, look);
      }
    };

    checkTaggedUrl(function(error, look) {
      if (error || !look) {
        callback("error - " + error, null);
      } else {
        var ret = "<img src='" + look.taggedUrl + "' usemap='#ascot" + look._id + "'>";
        ret += "<map name='ascot" + look._id + "'>";
        for (var i = 0; i < look.tags.length; ++i) {
          ret += "<area shape='circle' coords='" + look.tags[i].position.x + "," + look.tags[i].position.y + ",12' href='" + look.tags[i].product.buyLink + "' target='_blank'>";
        }
        ret += "</map>";
        callback(null, ret);
      }
    });
  };
};